config/routes.rb
Rails.application.routes.draw do
  resources :courses
  get 'pages/about'
  get 'pages/location'

  root 'pages#home' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord

  def star_number
    self.star.blank? ? 1 : self.star
  end

  def cover
    self.image.blank? ? "default.png" : self.image
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:image, :video, :title, :star, :description, :public)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def location
  end

  def home
   @courses = Course.where(public: true)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <p>    <%= form.text_field :image, placeholder: "Image", class: "form-control" %></p>
  </div>

  <div class="form-group">
    <p>  <%= form.text_field :video, placeholder: "Video", class: "form-control" %></p>
  </div>

  <div class="form-group">
    <p>  <%= form.text_field :title, placeholder: "Name", class: "form-control" %></p>
  </div>

  <div class="form-group">
    <p>  <%= form.number_field :star, placeholder: "Rating", class: "form-control" %></p>
  </div>

  <div class="field">
  <p>  <%= form.text_area :description, placeholder: "Description",length: "800", class: "form-control" %> </p>
  </div>
  <div class="form-check">
  <%= form.check_box :public, id: :public, class: "form-check-input"%>
  <label for="public" class="form-check-label">Publish?</label>
  </div>
<br>
  <button type="submit" class="btn btn-primary">Save</button>
  <%= link_to "Show all", courses_path, class: "btn btn-secondary" %>


<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<%= link_to 'New Course', new_course_path, class: "btn btn-primary" %>

<table class="table table-border-less">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td>
          <%= link_to course.title, course %>
<td>

      <%= link_to edit_course_path(course) do %>
      <i class="fas fa-edit"></i>
      <% end %>
        <%= link_to course, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="fas fa-trash"></i>
          <% end %>
            </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

app/views/courses/show.html.erb
<div id="ytplayer"></div>

<script>
  // Load the IFrame Player API code asynchronously.
  var tag = document.createElement('script');
  tag.src = "https://www.youtube.com/player_api";
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

  // Replace the 'ytplayer' element with an <iframe> and
  // YouTube player after the API code downloads.
  var player;
  function onYouTubePlayerAPIReady() {
    player = new YT.Player('ytplayer', {
      height: '360',
      width: '100%',
      videoId: '<%= @course.video %>'
    });
  }
</script>


<div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-4">
    <%= image_tag @course.cover, class: "card-img" %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= @course.title %></h5>
        <% (1..@course.star_number).each do %>
        <i class="fas fa-star"></i>
          <% end %>
        <p class="card-text"><%= @course.description %></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstUdemy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/58d5dcb1ab.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="<%= root_path %>">Andrii</a>
      <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="<%= courses_path %>">Courses <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= pages_about_path %>">About projects</a>
        </li>
        <li class="nav-item">
        <%= link_to "Contacts", pages_location_path, class: "nav-link" %>
        </li>
      </ul>

    </div>

</nav>
<div class="container pt-4">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <%= yield %>

    </div>

  </div>

</div>
  </body>
</html>

app/views/pages/about.html.erb
<h2>About projects</h2>
<div class="card shadow p-3 md-5 bg-white rounder">
<div class="card-body">
  <div class="row">
    <div class="col-md-6">
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Sunsets don&#39;t get much better than this one over <a href="https://twitter.com/GrandTetonNPS?ref_src=twsrc%5Etfw">@GrandTetonNPS</a>. <a href="https://twitter.com/hashtag/nature?src=hash&amp;ref_src=twsrc%5Etfw">#nature</a> <a href="https://twitter.com/hashtag/sunset?src=hash&amp;ref_src=twsrc%5Etfw">#sunset</a> <a href="http://t.co/YuKy2rcjyU">pic.twitter.com/YuKy2rcjyU</a></p>&mdash; US Department of the Interior (@Interior) <a href="https://twitter.com/Interior/status/463440424141459456?ref_src=twsrc%5Etfw">May 5, 2014</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
    <div class="col-md-6">
       <div class="card-body shadow-sm p-3 mb-5 bg-white rounded">
          <div class="row">
            <div class="col-md-3">
           <%= image_tag "1.jpg", class: "rounded-circle img-fluid" %>

        </div>
        <div class="col-md-9">
 <span>
 <h5>Andrii Ivaniuk</h5>
 Student Ruby
 </span>
        </div>
       </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/pages/home.html.erb
<br>

<div class="row">
  <%= @courses.each do |course| %>
<div class="col-md-4">
  <div class="card">
    <%= link_to course do %>
    <%= image_tag course.cover, class: "card-img-top" %>
    <% end %>
    <div class="card-body">
      <h5 class="card-title"><%= course.title %></h5>
      <% (1..course.star_number).each do %>
      <i class="fas fa-star"></i>
        <% end %>
    </div>
  </div>
</div>
  <% end %>
</div>

app/views/pages/location.html.erb
<h2>Contacts</h2>
<div class="card shadow p-3 mb-5 bg-white rounded">
  <div class="card-body">
    <div class="row">
      <p>You find us here!</p>
  <div style="overflow:hidden;width: 700px;position: relative;"><iframe width="1200" height="540" src="https://maps.google.com/maps?width=700&amp;height=440&amp;hl=en&amp;q=Ivano-Frankivsk+(My%20location)&amp;ie=UTF8&amp;t=k&amp;z=13&amp;iwloc=B&amp;output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><div style="position: absolute;width: 80%;bottom: 10px;left: 0;right: 0;margin-left: auto;margin-right: auto;color: #000;text-align: center;"><small style="line-height: 1.8;font-size: 2px;background: #fff;">Powered by <a href="https://embedgooglemaps.com/en/">embedgooglemaps EN</a> & <a href="https://embedvimeovideo.com">How to embed vimeo video</a></small></div><style>#gmap_canvas img{max-width:none!important;background:none!important}</style></div><br />
  </div>
</div>